/**
 * Tests for the CASUAL / FORMAL / WARM filler pools.
 *
 * These fillers are pre-generated by fillers-cache.ts and played on Telnyx
 * media streams while the LLM is thinking. The tests cover:
 *  1. Each style returns its expected, non-empty pool
 *  2. The pools are disjoint (no duplicate filler across styles)
 *  3. getRandomFiller always returns a member of the requested pool
 *  4. The three styles are differentiated (no two pools are identical)
 *  5. Every filler ends with an ellipsis (UX convention: "I'm thinking…")
 */

import { describe, it, expect } from 'vitest';
import {
  CASUAL_FILLERS,
  FORMAL_FILLERS,
  WARM_FILLERS,
  getFillers,
  getRandomFiller,
} from '../fillers';

describe('fillers — getFillers()', () => {
  it('returns the CASUAL pool for "CASUAL"', () => {
    expect(getFillers('CASUAL')).toBe(CASUAL_FILLERS);
  });

  it('returns the FORMAL pool for "FORMAL"', () => {
    expect(getFillers('FORMAL')).toBe(FORMAL_FILLERS);
  });

  it('returns the WARM pool for "WARM"', () => {
    expect(getFillers('WARM')).toBe(WARM_FILLERS);
  });

  it('every pool is non-empty (>= 5 fillers per style)', () => {
    expect(CASUAL_FILLERS.length).toBeGreaterThanOrEqual(5);
    expect(FORMAL_FILLERS.length).toBeGreaterThanOrEqual(5);
    expect(WARM_FILLERS.length).toBeGreaterThanOrEqual(5);
  });

  it('no filler is duplicated within a single pool', () => {
    for (const [name, pool] of [
      ['CASUAL', CASUAL_FILLERS],
      ['FORMAL', FORMAL_FILLERS],
      ['WARM', WARM_FILLERS],
    ] as const) {
      expect(new Set(pool).size, `${name} pool has duplicates`).toBe(pool.length);
    }
  });

  it('the three pools are pairwise disjoint', () => {
    const all = new Set<string>([...CASUAL_FILLERS, ...FORMAL_FILLERS, ...WARM_FILLERS]);
    const totalLength = CASUAL_FILLERS.length + FORMAL_FILLERS.length + WARM_FILLERS.length;
    expect(all.size).toBe(totalLength);
  });

  it('the three styles are visibly differentiated (no pool is a copy of another)', () => {
    expect(CASUAL_FILLERS).not.toEqual(FORMAL_FILLERS);
    expect(CASUAL_FILLERS).not.toEqual(WARM_FILLERS);
    expect(FORMAL_FILLERS).not.toEqual(WARM_FILLERS);
  });

  it('every filler ends with an ellipsis (… or ...) to signal "still thinking"', () => {
    const all = [...CASUAL_FILLERS, ...FORMAL_FILLERS, ...WARM_FILLERS];
    const offenders = all.filter((f) => !/(…|\.\.\.)\s*$/.test(f));
    expect(offenders, `fillers without trailing ellipsis: ${JSON.stringify(offenders)}`).toEqual(
      [],
    );
  });
});

describe('fillers — getRandomFiller()', () => {
  it('returns a member of the requested pool', () => {
    for (const style of ['CASUAL', 'FORMAL', 'WARM'] as const) {
      const pool = getFillers(style);
      for (let i = 0; i < 25; i++) {
        const picked = getRandomFiller(style);
        expect(pool, `style=${style} pick=${picked}`).toContain(picked);
      }
    }
  });

  it('eventually picks more than one distinct filler (random distribution is alive)', () => {
    const picked = new Set<string>();
    // 100 draws from CASUAL — pool is ~10 → should hit at least 3 distinct values
    for (let i = 0; i < 100; i++) picked.add(getRandomFiller('CASUAL'));
    expect(picked.size).toBeGreaterThanOrEqual(3);
  });

  it('returns strings (never undefined/empty)', () => {
    for (const style of ['CASUAL', 'FORMAL', 'WARM'] as const) {
      const picked = getRandomFiller(style);
      expect(typeof picked).toBe('string');
      expect(picked.length).toBeGreaterThan(0);
    }
  });
});
