#!/bin/bash
# Fetch Cloudflare IP ranges and regenerate
# infra/nginx/snippets/sokar-cloudflare-real-ip.conf.
#
# Usage: bash scripts/ops/update-cloudflare-ips.sh
#        sudo bash scripts/ops/update-cloudflare-ips.sh  # to install into Nginx
#
# Cloudflare publishes the canonical lists at:
#   https://www.cloudflare.com/ips-v4
#   https://www.cloudflare.com/ips-v6

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
OUT_FILE="$ROOT/infra/nginx/snippets/sokar-cloudflare-real-ip.conf"

fetch_ips() {
  curl -sS "$1" || {
    echo "❌ Failed to fetch $1" >&2
    exit 1
  }
}

V4_IPS=$(fetch_ips 'https://www.cloudflare.com/ips-v4')
V6_IPS=$(fetch_ips 'https://www.cloudflare.com/ips-v6')

cat > "$OUT_FILE" <<'HEADER'
# Cloudflare IPv4/IPv6 ranges used for `set_real_ip_from`.
# These are the canonical Cloudflare IP ranges, generated by scripts/ops/update-cloudflare-ips.sh.
# Refresh them periodically by running that script.
# If the list becomes stale, the `real_ip_header` may trust a non-Cloudflare IP and
# expose the wrong client IP to upstream services.

real_ip_header CF-Connecting-IP;
real_ip_recursive on;

HEADER

while IFS= read -r cidr; do
  [ -n "$cidr" ] && echo "set_real_ip_from $cidr;"
done <<< "$V4_IPS" >> "$OUT_FILE"

while IFS= read -r cidr; do
  [ -n "$cidr" ] && echo "set_real_ip_from $cidr;"
done <<< "$V6_IPS" >> "$OUT_FILE"

echo "✅ $OUT_FILE updated ($(echo "$V4_IPS" | grep -c '^' || true) v4 + $(echo "$V6_IPS" | grep -c '^' || true) v6 ranges)."
